In [1]:
import pandas as pd
import numpy as np

Bag of words

In [2]:
df = pd.DataFrame({"text":['people watch ds',
                           'ds watch ds',
                           'people write comment',
                           'ds write comment'],"output":[1,1,0,0]})

In [3]:
df

,text,output
0,people watch ds,1
1,ds watch ds,1
2,people write comment,0
3,ds write comment,0


In [4]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer()

In [5]:
bow = cv.fit_transform(df['text'])

In [6]:
print(cv.vocabulary_)

{'people': 2, 'watch': 3, 'ds': 1, 'write': 4, 'comment': 0}


In [7]:
print(bow.toarray())

[[0 1 1 1 0]
 [0 2 0 1 0]
 [1 0 1 0 1]
 [1 1 0 0 1]]


BIgram BOW

In [8]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(ngram_range=(2,2))

In [10]:
bow = cv.fit_transform(df['text'])

In [13]:
print(cv.vocabulary_)

{'people watch': 2, 'watch ds': 4, 'ds watch': 0, 'people write': 3, 'write comment': 5, 'ds write': 1}


In [14]:
print(bow.toarray())

[[0 0 1 0 1 0]
 [1 0 0 0 1 0]
 [0 0 0 1 0 1]
 [0 1 0 0 0 1]]


Tigram BOW

In [15]:
cv = CountVectorizer(ngram_range=(3,3))

In [16]:
bow = cv.fit_transform(df['text'])

In [17]:
print(cv.vocabulary_)

{'people watch ds': 2, 'ds watch ds': 0, 'people write comment': 3, 'ds write comment': 1}


In [18]:
print(bow.toarray())

[[0 0 1 0]
 [1 0 0 0]
 [0 0 0 1]
 [0 1 0 0]]
